"""create figure_text_matches

Revision ID: 24af77533a2b
Revises: fb7eab2e5c35
Create Date: 2026-07-13 09:39:31.072321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24af77533a2b'
down_revision: Union[str, None] = 'fb7eab2e5c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('figure_text_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('figure_id', sa.UUID(), nullable=False),
    sa.Column('paragraph_id', sa.UUID(), nullable=False),
    sa.Column('match_type', sa.String(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('quote_span', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['figure_id'], ['figures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paragraph_id'], ['paragraphs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_figure_text_matches_figure_id'), 'figure_text_matches', ['figure_id'], unique=False)
    op.create_index(op.f('ix_figure_text_matches_paragraph_id'), 'figure_text_matches', ['paragraph_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_figure_text_matches_paragraph_id'), table_name='figure_text_matches')
    op.drop_index(op.f('ix_figure_text_matches_figure_id'), table_name='figure_text_matches')
    op.drop_table('figure_text_matches')
    # ### end Alembic commands ###
