"""create figure_explanations

Revision ID: 25ce680a8378
Revises: 24af77533a2b
Create Date: 2026-07-13 14:13:14.292479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25ce680a8378'
down_revision: Union[str, None] = '24af77533a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('figure_explanations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('figure_id', sa.UUID(), nullable=False),
    sa.Column('figure_type', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detailed_explanation', sa.Text(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grounding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['figure_id'], ['figures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_figure_explanations_figure_id'), 'figure_explanations', ['figure_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_figure_explanations_figure_id'), table_name='figure_explanations')
    op.drop_table('figure_explanations')
    # ### end Alembic commands ###
